### ISSUE TITLE
Improve debuging problem with deployments

### ISSUE THREAD

**Issue by miry** [jgaskins/rails_app_operator#1]
I am starting checking the operator.

Created a sample rails app resource and looking for ways to debug the problem.
The current logs looks not very informative:

```console
$ kubectl -n rails-app-operator logs -f rails-app-controller-7b6bbb54c6-qkxnc
2024-04-27T21:40:11.738125Z   INFO - rails-app-operator: Watching Rails Apps
2024-04-27T21:50:11.725411Z   WARN - kubernetes.client: End of file reached
```

PS: I am going to dive more in the reasons of my bad deployment, I am pretty sure I did something wrong. Created this issue as placeholder for my future investigations.

## Details

```
$ kubectl version                                               
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
```

<details><summary>RailsApp Resources</summary>
<p>

```yaml
---
apiVersion: jgaskins.dev/v1beta1
kind: RailsApp
metadata:
  name: <name>
  namespace: <namespace>

spec:
  image: <private repo>
  image_pull_policy: Always

  env:
    - name: PORT
      value: "8080"
    - name: RAILS_MAX_THREADS
      value: "16"
    - name: WEB_CONCURRENCY
      value: "0"

  envFrom:
    - configMapRef:
        name: env
    - secretRef:
        name: env

  entrypoints:
    - name: web
      command: [bundle, exec, puma, -C, config/puma.rb]
      port: 8080
      replicas: 2
      resources:
        requests:
          memory: "500Mi"
        limits:
          memory: "1Gi"

    - name: sidekiq
      command: [bundle, exec, sidekiq]
      replicas: 1
      resources:
        requests:
          memory: "200Mi"
        limits:
          memory: "500Mi"

  before_update:
    command: [bundle, exec, rails, db:migrate:with_data]
```

</p>
</details>
